# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]            # The name of the module we are configuring is "character"
success_symbol = "âœ"   # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 500
# $duration â€“ The command duration (e.g. "15s")
# $style    â€“ The default style of the module (e.g. "bold yellow")
format = "underwent [$duration]($style) "

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false
